#  <center> K Nearest Neighbors

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
plt.style.use("ggplot")
from sklearn import neighbors
from sklearn.model_selection import cross_validate, train_test_split
from sklearn.metrics import classification_report

In [2]:
data = pd.read_csv("../datasets/cancer/breast-cancer-wisconsin.data.txt")
data

name  v1  v2  v3  v4  v5  v6  v7  v8  v9  class
0    1000025   5   1   1   1   2   1   3   1   1      2
1    1002945   5   4   4   5   7  10   3   2   1      2
2    1015425   3   1   1   1   2   2   3   1   1      2
3    1016277   6   8   8   1   3   4   3   7   1      2
4    1017023   4   1   1   3   2   1   3   1   1      2
..       ...  ..  ..  ..  ..  ..  ..  ..  ..  ..    ...
694   776715   3   1   1   1   3   2   1   1   1      2
695   841769   2   1   1   1   2   1   1   1   1      2
696   888820   5  10  10   3   7   3   8  10   2      4
697   897471   4   8   6   4   3   4  10   6   1      4
698   897471   4   8   8   5   4   5  10   4   1      4

[699 rows x 11 columns]

In [3]:
data = data.apply(lambda x: x.replace("?", -9999999)) # Un numero muy pequeño para que no afecte en la decisión

In [4]:
data.loc[:,:] = np.array(data,dtype = np.float32)

In [5]:
# data.replace("?",-99999999, inplace = True)

In [6]:
data.describe()

name          v1          v2          v3          v4  \
count  6.990000e+02  699.000000  699.000000  699.000000  699.000000   
mean   1.071704e+06    4.417740    3.134478    3.207439    2.806867   
std    6.170957e+05    2.815741    3.051459    2.971913    2.855379   
min    6.163400e+04    1.000000    1.000000    1.000000    1.000000   
25%    8.706885e+05    2.000000    1.000000    1.000000    1.000000   
50%    1.171710e+06    4.000000    1.000000    1.000000    1.000000   
75%    1.238298e+06    6.000000    5.000000    5.000000    4.000000   
max    1.345435e+07   10.000000   10.000000   10.000000   10.000000   

               v5            v6          v7          v8          v9  \
count  699.000000  6.990000e+02  699.000000  699.000000  699.000000   
mean     3.216023 -2.288949e+05    3.437768    2.866953    1.589413   
std      2.214300  1.496595e+06    2.438364    3.053634    1.715078   
min      1.000000 -9.999999e+06    1.000000    1.000000    1.000000   
25%      2.000000  1.000000e+00    2.000000    1.000000    1.000000   
50%      2.000000  1.000000e+00    3.000000    1.000000    1.000000   
75%      4.000000  5.000000e+00    5.000000    4.000000    1.000000   
max     10.000000  1.000000e+01   10.000000   10.000000   10.000000   

            class  
count  699.000000  
mean     2.689557  
std      0.951273  
min      2.000000  
25%      2.000000  
50%      2.000000  
75%      4.000000  
max      4.000000

In [7]:
X = data.iloc[:,1:-1]
Y = data["class"]

## <center>Clasificador de los K vecinos

In [8]:
X_train,X_test,Y_train,Y_test =train_test_split(X,Y, test_size = 0.2)

In [9]:
clf = neighbors.KNeighborsClassifier()

In [10]:
clf.fit(X_train,Y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [11]:
accuracy = clf.score(X_train,Y_train)
accuracy

0.9803220035778175

## <center>Clasificación sin limpieza

In [12]:
data = pd.read_csv("../datasets/cancer/breast-cancer-wisconsin.data.txt").replace("?",-9999999)
X = data.iloc[:,:-1]
Y = data["class"]
X_train,X_test,Y_train,Y_test =train_test_split(X,Y, test_size = 0.2)
clf = neighbors.KNeighborsClassifier()
clf.fit(X,Y)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [13]:
accuracy = clf.score(X_train,Y_train)
accuracy

0.7692307692307693

## <center> Clasificar los datos nuevos

In [14]:
# Valores
np.unique(data.iloc[:,-1])

array([2, 4], dtype=int64)

In [15]:
data = pd.read_csv("../datasets/cancer/breast-cancer-wisconsin.data.txt").replace("?",-9999999)
X = data.iloc[:,1:-1]
Y = data["class"]
X_train,X_test,Y_train,Y_test =train_test_split(X,Y, test_size = 0.2)
clf = neighbors.KNeighborsClassifier()
clf.fit(X,Y)
accuracy = clf.score(X_train,Y_train)
accuracy

0.9785330948121646

In [16]:
print(classification_report(clf.predict(X_test),Y_test))

              precision    recall  f1-score   support

           2       0.96      1.00      0.98        95
           4       1.00      0.91      0.95        45

    accuracy                           0.97       140
   macro avg       0.98      0.96      0.97       140
weighted avg       0.97      0.97      0.97       140



In [17]:
np.mean([clf.predict(X_test) == Y_test])

0.9714285714285714

In [18]:
[clf.predict(np.sign(np.random.randint(-9,9))*np.random.randint(-9,9,(1,9))) for l in range(10)]# Predecir valores random

[array([2], dtype=int64),
 array([2], dtype=int64),
 array([2], dtype=int64),
 array([2], dtype=int64),
 array([2], dtype=int64),
 array([4], dtype=int64),
 array([2], dtype=int64),
 array([2], dtype=int64),
 array([2], dtype=int64),
 array([2], dtype=int64)]